// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Minio.FileSystem.Backend;

#nullable disable

namespace Minio.FileSystem.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231113110155_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Minio.FileSystem.Backend.FileSystemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("FileSystems");
                });

            modelBuilder.Entity("Minio.FileSystem.Backend.FileSystemItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FileSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FileSystemItemType")
                        .HasColumnType("int");

                    b.Property<string>("MetaProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("VirtualPath")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FileSystemId");

                    b.HasIndex("ParentId");

                    b.HasIndex("TenantId");

                    b.HasIndex("VirtualPath");

                    b.ToTable("FileSystemItems");
                });

            modelBuilder.Entity("Minio.FileSystem.Backend.FileSystemItemEntity", b =>
                {
                    b.HasOne("Minio.FileSystem.Backend.FileSystemEntity", "FileSystem")
                        .WithMany("FileSystemItems")
                        .HasForeignKey("FileSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Minio.FileSystem.Backend.FileSystemItemEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("FileSystem");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Minio.FileSystem.Backend.FileSystemEntity", b =>
                {
                    b.Navigation("FileSystemItems");
                });

            modelBuilder.Entity("Minio.FileSystem.Backend.FileSystemItemEntity", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
